"""Login to string

Revision ID: 3dcb0480e7aa
Revises: 45aed335cb2f
Create Date: 2025-04-16 20:41:32.468229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcb0480e7aa'
down_revision: Union[str, None] = '45aed335cb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
